### ISSUE TITLE
Influx-DB Latest enforces authentication 

### ISSUE THREAD

**Issue by qubeio** [PacktPublishing/Learn-Grafana-7.0#2]
As per comment, using the latest InfluxDB image causes the upload script (Chapter 05) to fail with a 401. Changing the docker-compose file to InfluxDB:1.7.0 fixed it (though I don't know exactly which version you need to go back to)

Just in case anyone else ends up here for the same reason

**Comment by sonam-packt** [comment]
HI @AndreasFrangopoulos,

Thank you for the suggestion, it might help other readers too.

Thanks!

**Comment by dal233** [comment]
Hello @AndreasFrangopoulos,

I have encountered this issue too.  Do you mean to edit this code?

```
version: "3"

services:
  grafana:
    image: "grafana/grafana:${GRAF_TAG-latest}"
    ports:
      - "3000:3000"
    volumes:
      - "${PWD-.}/grafana:/var/lib/grafana"

  influxdb:
    image: "influxdb:${INFL_TAG-latest}"
    ports:
      - "8086:8086"
    volumes:
      - "${PWD-.}/influxdb:/var/lib/influxdb"
```

**Comment by dal233** [comment]
Answering my own question, you need to change your influxdb image to the below in the docker-compose.yml file.

```
  influxdb:
    image: "influxdb:1.7.0"
    ports:
      - "8086:8086"
    volumes:
      - "${PWD-.}/influxdb:/var/lib/influxdb"

```
